### ISSUE TITLE
SPARQL end-point

### ISSUE THREAD

**Issue by ldesousa** [soilwise-he/soilwise-architecture#13]
There is no SPARQL end-point in the diagram at this moment. Was it removed? Or did it never feature? I recall it being discussed during the KoM.

For further clarification.

**Comment by DajanaSnopkova** [comment]
It was in the Kick-off meeting architecture. For this consolidated version, I aggregated all data preview and publication APIs to one component (Data preview and publication APIs - SparQL is in the bracket) to simplify the diagram since I expected similar relationships for all of them. However, maybe that was not a good decision.

**Comment by pvgenuchten** [comment]
I assume the sparql endpoint will not support transactions (seems the standard does not describe transactions, but [some products support it](https://stackoverflow.com/questions/54581081/sparql-transaction)). In that case the sparql endpoint can indeed be seen as one of the potential query endpoints, however the triplestore backend is probably a different one then other api's (usually a relational or object database)
