### ISSUE TITLE
documention in github

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/soilwise-architecture#14]
at the meeting today it was mentioned that we're looking for a technology for publishing documentation maintained in git

i think we have 3 options:
- [mkdocs](https://mkdocs.org) pythonic tool for documentation
- [quarto](https://quarto.org), used frequently at isric, can also be used to generate [slides](https://quarto.org/docs/presentations/), option to include python scripts for dedicated map/diagram output
- [gitbook](https://www.gitbook.com/); one of the default recipes in github

Related technology
- Use of [mermaid](https://mermaid.js.org/) for diagrams

**Comment by ldesousa** [comment]
I have been using [Pandoc](https://pandoc.org/) since 2021 and am very happy with it, far more flexible than Quarto. My book is all managed with Pandoc.

However, since it will be @DajanaSnopkova leading the process, the wisest choice is the technology with which she is most confortable.

**Comment by DajanaSnopkova** [comment]
From my experience, the biggest issue is to set up the repository, add all plugins and pipeline for automatic build. So it depends on who will be responsible for this part, that one should be familiar with the selected option. I will gladly give up this responsibility 😄, since I have previously only worked with mkdocs, but we were using it only for User Manuals. 

Honestly, I have a bit of a problem seeing into the future and estimating what we will need documentation for. If we set up something now, it should not be only for the purpose of the Archi deliverable... I assume that in the future it would be good for each component to have the documentation in its own repository (I am based on the modular principle of SWR), and then somehow it would be put together and published in one place. What do you think?

**Comment by pvgenuchten** [comment]
Hi see for example the [pipeline based on quarto](https://github.com/ejpsoil/soildata-assimilation-guidance/blob/main/.github/workflows/deploy.docs.yml), which manages to update the ejpsoil soil data assimilation guidance cookbook. At changes the content is published at ejpsoil.github.io/soildata-assimilation-guidance
